//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книжный
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Жанр { get; set; }
        public string Автор { get; set; }
        public int Колво_магаз { get; set; }
        public int Колво_склад { get; set; }
        public string Описание { get; set; }
        public string Обложка { get; set; }
        public Nullable<decimal> Цена { get; set; }
    }
}
